print("Введите отчетный месяц")
month = input()
print("Введите отчетный год")
year = input()
print("Сколько долларов Вы потратили на питание в " + month + " " + year + " года?")
food = int(input())
print("Сколько долларов Вы потратили на одежду и обувь в " + month + " " + year + " года?")
clothes = int(input())
print("Сколько долларов Вы потратили на коммунальные услуги, интернет, телефон в " + month + " " + year + " года?")
utilities = int(input())
print("Сколько долларов Вы потратили на товары для дома в " + month + " " + year + " года?")
home = int(input())
print("Сколько долларов Вы потратили на детей в " + month + " " + year + " года?")
child = int(input())
print("Сколько долларов Вы потратили на выплату задолженностей в " + month + " " + year + " года?")
credit = int(input())
print("Сколько долларов Вы потратили на транспорт (авто, общественный, такси) в " + month + " " + year + " года?")
transport = int(input())
print("Сколько долларов Вы потратили на вклад в банк в " + month + " " + year + " года?")
deposit = int(input())
print("Сколько долларов Вы потратили на развлечения в " + month + " " + year + " года?")
game = int(input())
print("Сколько долларов Вы потратили на личные расходы в " + month + " " + year + " года?")
person = int(input())
expenses = str(food + clothes + utilities + home + child + credit + transport + deposit + game + person)
print("Сумма ваших расходов за " + month + " " + year + " года равна " +expenses)