print("Как Вас зовут?")
name = input()
print("Сколько Вам полных лет?")
age = int(input())
print("Укажите вашу дату рождения")
dateOfBirth = input()
print("Укажите Вы женаты/замужем")
married = input()
print("Укажите, сколько у Вас детей")
child = int(input())
print("Вас зовут " +name+ ", Вам " +str(age)+ " лет, Вы родились " +dateOfBirth+ ". Вы " +married+ ". У Вас " +str(child)+ " детей.")
